GraduationProject/Controllers/ManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DHD.ENTITY;
using DHD.BLL;
using GraduationProject.Models;
using GraduationProject.Filters;
namespace GraduationProject.Controllers
{
    public class ManagerController : Controller
    {
        // GET: Manager
        ManagerBll bll = new ManagerBll();
        public ActionResult Register()
        {
            return View();
        }
        public ActionResult Login()
        {
            return View();
        }
        public ActionResult EnterForBack()
        {
            return View();
        }
        public ActionResult LoginValidate(BackLoginModel loginModel)
        {
            if (ModelState.IsValid)
            {
                var manager = bll.GetAll().Where(d => d.UserName == loginModel.UserName).FirstOrDefault();
                if (manager != null)
                {
                    if (manager.Password == loginModel.Password)
                    {
                        HttpCookie cookie = new HttpCookie("managerId");
                        cookie.Value = manager.Id.ToString();
                        HttpContext.Response.Cookies.Add(cookie);

                        return RedirectToAction("Index", "Schools");
                    }
                    else
                    {
                        ModelState.AddModelError("", "密码错误！");
                    }
                }
                else
                {
                    ModelState.AddModelError("", "用户名不存在！");
                }
            }
            return View("Login",loginModel);
        }
        public ActionResult RegisterValidate(BackRegisterModel registerModel)
        {
            if (ModelState.IsValid)
            {
                var manager = bll.GetAll().Where(d => d.UserName == registerModel.UserName).FirstOrDefault();
                if (manager == null)
                {
                    var newManager = new Manager();
                    newManager.UserName = registerModel.UserName;
                    newManager.NickName = registerModel.NickName;
                    newManager.Password = registerModel.Password;
                    manager = bll.Add(newManager);
                    HttpCookie cookie = new HttpCookie("managerId");
                    cookie.Value = manager.Id.ToString();
                    HttpContext.Response.Cookies.Add(cookie);
                    return RedirectToAction("Index", "Schools");
                }
                else
                {
                    ModelState.AddModelError("", "用户名已存在！");
                }
            }
            // If we got this far, something failed, redisplay form
            return View("Register",registerModel);
        }
        public ActionResult LogOut()
        {
            return View("");
        }
    }
}

GraduationProject/Views/Manager/Login.cshtml
@model GraduationProject.Models.BackLoginModel
@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/BackEnter.cshtml";
}
<div class="login" style="margin-top:100px;">
    <div class="header">
        <div class="switch" id="switch">
            <a class="switch_btn_focus" id="switch_qlogin" href="javascript:void(0);" tabindex="7">快速登录</a>
            <a class="switch_btn" id="switch_login" href="javascript:void(0);" tabindex="8">快速注册</a>
            <div class="switch_bottom" id="switch_bottom" style="position: absolute; width: 64px; left: 0px;"></div>
        </div>
    </div>
    <div class="web_qr_login" id="web_qr_login" style="display: block; height: 235px;">
        <!--登录-->
        <div class="web_login" id="web_login">
            <div class="login-box">
                <div class="login_form">
                    @using (Html.BeginForm("LoginValidate", "Manager", new { @class = "loginFomm" }))
                    {
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary()
                        <input type="hidden" name="did" value="0" />
                        <input type="hidden" name="to" value="log" />
                        <div class="uinArea" id="uinArea">
                            @Html.LabelFor(m => m.UserName, new { @class = "input-tips" })
                            <div class="inputOuter" id="uArea">
                                @Html.TextBoxFor(m => m.UserName, new { @class = "inputstyle" })
                                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
                            </div>
                            
                        </div>
                        <div class="pwdArea" id="pwdArea">
                            @Html.LabelFor(m => m.Password, new { @class = "input-tips" })
                            <div class="inputOuter" id="pArea">
                                @Html.TextBoxFor(m => m.Password, new { @class = "inputstyle" ,type="password"})
                                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                            </div>
                            
                        </div>
                        <div style="padding-left:50px;margin-top:20px;"><input type="submit" value="登 录" style="width:150px;" class="button_blue" /></div>
                    }
                </div>
            </div>
        </div>
        <!--登录end-->
    </div>
</div>

GraduationProject/Views/Manager/Register.cshtml
@model GraduationProject.Models.BackRegisterModel
@{
    ViewBag.Title = "Register";
    Layout = "~/Views/Shared/BackEnter.cshtml";
}
<div class="login" style="margin-top:100px;">
    <div class="header">
        <div class="switch" id="switch">
            <a class="switch_btn" id="switch_qlogin" href="javascript:void(0);" tabindex="7">快速登录</a>
            <a class="switch_btn_focus" id="switch_login" href="javascript:void(0);" tabindex="8">快速注册</a>
            <div class="switch_bottom" id="switch_bottom" style="position: absolute; width: 64px; left: 154px;"></div>
        </div>
    </div>
    <!--注册-->
    <div class="qlogin" id="qlogin">
        <div class="web_login" id="web_login">
            <div class="login-box">
                <div class="login_form">
                    @using (Html.BeginForm("RegisterValidate", "Manager", new { @class = "loginFomm" }))
                    {
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary()
                        <input type="hidden" name="did" value="0" />
                        <input type="hidden" name="to" value="log" />
                        <div class="uinArea" id="uinArea">
                            @Html.LabelFor(m => m.UserName, new { @class = "input-tips" })
                            <div class="inputOuter" id="uArea">
                                @Html.TextBoxFor(m => m.UserName, new { @class = "inputstyle" })
                                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="uinArea" id="uinArea">
                            @Html.LabelFor(m => m.NickName, new { @class = "input-tips" })
                            <div class="inputOuter" id="uArea">
                                @Html.TextBoxFor(m => m.NickName, new { @class = "inputstyle" })
                                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="pwdArea" id="pwdArea">
                            @Html.LabelFor(m => m.Password, new { @class = "input-tips" })
                            <div class="inputOuter" id="pArea">
                                @Html.TextBoxFor(m => m.Password, new { @class = "inputstyle" ,type="password"})
                                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="pwdArea" id="pwdArea">
                            @Html.LabelFor(m => m.Password2, new { @class = "input-tips" ,type="password"})
                            <div class="inputOuter" id="pArea">
                                @Html.TextBoxFor(m => m.Password2, new { @class = "inputstyle" })
                                @Html.ValidationMessageFor(model => model.Password2, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="inputArea">
                            <input type="submit" id="reg" style="margin-top:10px;margin-left:65px;" class="button_blue" value="同意协议并注册" /> <a href="#" class="zcxy" target="_blank">注册协议</a>
                        </div>
                        <div class="cl"></div>
                    }
                </div>
            </div>
        </div>
    </div>
    <!--注册end-->
</div>